### PR TITLE
Add automatic version detection to Javadoc badge

### PR DESCRIPTION
**Pull request by valery1707**

### CODE REVIEW

**Comment by karato** [comment]
@valery1707 Many thanks, I will find someone to review it before we merge

**Comment by karato** [comment]
@yegor256 review it please, it is a rather short pull request, no need to do a full code review

**Comment by yegor256** [comment]
@rultor merge

**Comment by karato** [comment]
@yegor256 **16 mins** added to your account (payment number `000-32619236`), many thanks for your contribution! 72 hours and 47 mins spent here.; review comments (c=1) added as a bonus; +16 added to your rating, current score is: [+1665](http://www.netbout.com/b/35008?open=rating)

**Comment by karato** [comment]
@rultor deploy now pls

**Pull request merged**
